# include: package:lint/analysis_options.yaml

# linter:
#   rules:
#     parameter_assignments: true
#     avoid_print: false

# analyzer:
#   exclude:
#     - '**.g.dart'
#     - '**.gr.dart'
#     - '**.freezed.dart'
#     - '**.config.dart'
    
#   errors:
#     argument_type_not_assignable: ignore
#     missing_required_param: error
#     parameter_assignments: error
#     missing_return: error
#     must_be_immutable: error
#     invalid_use_of_protected_member: error