include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    sort_constructors_first: true

analyzer:
  exclude:
    - '**.g.dart'
    - '**.gr.dart'
    - '**.freezed.dart'
    - '**.config.dart'
    
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    must_be_immutable: error
    invalid_use_of_protected_member: error