name: flutter_pattern_templates
description: Collection of best pattern and architecture for Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Material Design Transitions.
  animations: ^1.1.2

  # Allows Flutter apps to discover network connectivity and configure themselves accordingly.
  connectivity: ^0.4.9

  # Functional programming in Dart.
  dartz: ^0.9.1

  # A powerful Http client for Dart, which supports Interceptors,
  # Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^3.0.9

  # Easy and Fast internationalization for your Flutter Apps.
  easy_localization: ^2.3.2

  # Flutter package that helps implement the BLoC pattern.
  flutter_bloc: ^6.0.1

  # Hooks are a new kind of object that manages a Widget life-cycles.
  # They exist for one reason: increase the code-sharing between widgets by removing duplicates.
  flutter_hooks: ^0.12.0

  # Infinite scrolll for Flutter.
  flutter_pagewise: ^1.2.3

  # Annotation for package freezed.
  freezed_annotation: ^0.11.0

  # Get storage.
  get_storage: ^1.2.1

  # This is a simple Service Locator for Dart and Flutter projects.
  get_it: ^4.0.4

  # Injectable is a convenient code generator for get_it.
  injectable: ^1.0.2

  # For testing purposes.
  mockito: ^4.1.1

  # NoSQL persistent store database solution for single process io applications.
  sembast: ^2.4.7+4
  sembast_web: ^1.2.0
  encrypt: ^4.0.2
  crypto: ^2.1.5

  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^1.6.11

  # Better ID.
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  build_runner: ^1.10.1

  # Another code generator for unions/pattern-matching/copy.
  # Also has sealed class generator.
  freezed: ^0.11.4

  # Generator of injectable.
  injectable_generator: ^1.0.3

  # Convert model to map, etc.
  json_serializable: ^3.3.0

  # Is a hand-picked, open-source, community-driven collection of lint rules for Dart and Flutter projects.
  # This package can be used as a replacement for pedantic for those who prefer stricter rules.
  lint: ^1.2.0

dependency_overrides:
  # Remove error on build_runner.
  analyzer: "0.39.14"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - configs/
    - translations/
